### ISSUE TITLE
Error during integratethis move2archive in windows explorer in Windows 11 System

### ISSUE THREAD

**Issue by chaicurioquest** [novoid/move2archive#11]
I am getting an error during integratethis move2archieve in Windows Explorer

In Command _line(cmd):_
`C:\User\Name>integratethis move2archive --confirm`
**"ERROR    Sorry, this tool is only configured to integrate to Windows Explorer. More to come in the future".**

However, I can integrate appendfilename, date2name, filetags variants and Tagtree in Windows Explorer.

**Comment by novoid** [comment]
Background: integratethis had no support for move2archive. I implemented a draft support yesterday.
