### ISSUE TITLE
feature suggestion: implementation of a try/escape clause

### ISSUE THREAD

**Issue by nbehrnd** [novoid/move2archive#5]
Similar to a physical archive, I had to re-use some data of yesterday already stashed by move2archive and intended to clear the space again (now) by move2archvie.  While this didn't work for that there already is a file of same name in the current working directory and the archive, there were two other files so far never deposit into the archive:

![2022-09-15T17 38 32 -- screenshots](https://user-images.githubusercontent.com/19709084/190448412-f3715584-326a-412b-aaf4-b8e78327fe72.png)

Asking *what if*: what if move2archive's action would include a try/escape clause to the effect:
+ To prevent accidental lost, files of same name/same hash string in the current working directory and in the archive folder are not moved into the archive.  They however 
+ allow other files in the same working directory (without match in the archive folder) to be moved into the archive folder.

Maybe to check files to contain the same content *based on a hash* is safer than a check *based on file name* if file tags assigned and annotations (appendfilename) of different days differ.

**Comment by novoid** [comment]
Hi @nbehrnd, please do test the most recent version. I added a check for skipping existing files at the destination. The user needs to handle the clash after she gets notified.

**Comment by nbehrnd** [comment]
@novoid  Working with the revised *current* version (i.e., [063fe06](https://github.com/novoid/move2archive/commit/063fe065b56e2f51f6d01529c7488cf6a489c440) by Saturday 2022-09-18) indeed nicely provides the sought improved functionality.  Merci.

**Comment by novoid** [comment]
:-)

Yes, I was too convinced to have fixed the issue with the small change so that I didn't test it. That was - once again - a reality-check to me. 

Thanks for the idea, it will help myself as well although I don't think that I've overwritten data so far. Maybe I archived the same file again, that can be the case.
