### ISSUE TITLE
move into the archive appears hindered

### ISSUE THREAD

**Issue by nbehrnd** [novoid/move2archive#9]
Using the current implementation by 2023-06-11, the move of *an individual file* into the archive directory is dysfunctional.  It however is possible (from the CLI) to deposit a stack of multiple files *at once* into an archive folder.

Again, the log attached below documents an instance of Linux Debian 13/trixie (branch testing) with Python 3.11.4 as provided by the repositories of Debian.

[2023-07-14_report_move2archive_02.txt](https://github.com/novoid/move2archive/files/12051324/2023-07-14_report_move2archive_02.txt)

**Comment by novoid** [comment]
Damn. I fixed the issue on my side, re-released the pypy package but forgot to push to Github. 

Most probably, your issue is fixed with the update now. Sorry. If not, please re-open and drop me a line.
